title: GPR
description: Library for doing GPR (Gaussian Process Regression) in OCaml.  Comes with a command line application.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
